baseURL: "https://www.trisphoto.com/"
title: trisphoto
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

taxonomies:
  place: places
  person: people

params:
  env: production
  mainSections:
    - posts
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  profileMode:
    enabled: true
    title: Tristan Smith
    buttons:
      - name: Archive
        url: /about/
      - name: Trips
        url: /trips/

  socialIcons:
    - name: strava
      url: "https://www.strava.com/athletes/31753850"
    - name: github
      url: "https://github.com/stristan258"

  cover:
    hidden: false
    hiddenInList: false
    hiddenInSingle: false

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - identifier: trips
      name: Trips
      url: /trips/
      weight: 2
    - identifier: places
      name: Places
      url: /places/
      weight: 3
    - identifier: live map
      name: Live Map
      url: /live-map/
      weight: 4
    - identifier: archives
      name: Archive
      url: /archives/
      weight: 5

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true