[build]
  command = "hugo --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.165.0"

[functions]
  directory = "netlify/functions"

[dev]
  command = "hugo server --bind 0.0.0.0 --port 1313"
  targetPort = 1313
  port = 8888
